### ISSUE TITLE
is there a way to tweak the yellow color?

### ISSUE THREAD

**Issue by mattdimicelli** [manekinekko/windows-nt-vscode-theme#5]
Hello,
First of all thank you so much for this awesome theme!  I recently starting using React and I noticed that in my React files there is a lot of yellow coloring for the parens and the corchet-brackets (see the screenshot).  Maybe it's because my monitors are shoddy, but I'm 
having a hard time seeing it (contrast issues with the white background).  Is there any way to tweak this yellow color in VS Code?

Thank you in advance!

![yellow](https://user-images.githubusercontent.com/67718737/167264048-0a2b0741-4599-4c94-a7ab-e362c873799f.png)

**Comment by mattdimicelli** [comment]
Btw I read the color theme documentation that you linked to, however, I couldn't figure out how to change this particular yellow coloring...

**Comment by manekinekko** [comment]
Thank you for reporting this issue @mattdimicelli. Could you try the latest version (0.0.11) I just published and let me know if you still see the issue?

Here is a sample screenshot:
![image](https://user-images.githubusercontent.com/1699357/167272410-83774ac2-3b32-42c9-bdc0-0100bb7d7b07.png)


https://marketplace.visualstudio.com/items?itemName=wassimdev.windows-nt-vscode-theme

**Comment by mattdimicelli** [comment]
Hi manekinekko,

Thank you for following up and for the update!  Yes, it still looks very nice and it is now much easier for me to see those characters!

![yellow](https://user-images.githubusercontent.com/67718737/167279442-5692fb93-fd23-4bf7-97fe-93687b0d5e02.png)

Thank you and have a great weekend
